from my_project.nutrition.domain.nutrition.competition_past import CompetitionPast
from my_project.nutrition.domain.nutrition.day import Day
from my_project.nutrition.domain.nutrition.dish import Dish
from my_project.nutrition.domain.nutrition.nutritional_suplement import NutritionalSuplement
from my_project.nutrition.domain.nutrition.place import Place
from my_project.nutrition.domain.nutrition.shchedule import Shchedule
from my_project.nutrition.domain.nutrition.sport import Sport
from my_project.nutrition.domain.nutrition.sportsmen import Sportsmen
from my_project.nutrition.domain.nutrition.trainer import Trainer
